# EEG Pipeline Configuration (organized per script)

project:
  root: "."
  task: "thermalactive"
  subjects: ["000"]
  bids_root: "eeg_pipeline/bids_output"
  source_root: "eeg_pipeline/source_data"

paths:
  project_root: "."
  bids_root: "eeg_pipeline/bids_output"
  deriv_root: "eeg_pipeline/bids_output/derivatives"
  source_data: "eeg_pipeline/source_data"

event_columns:
  temperature: ["stimulus_temp", "stimulus_temperature", "temp", "temperature"]
  rating: ["vas_final_coded_rating", "vas_final_rating", "vas_rating", "pain_intensity", "pain_rating", "rating"]
  pain_binary: ["pain_binary_coded", "pain_binary", "pain"]

foundational_analysis:
  erp:
    picks: "eeg"
    combine: "gfp"
    include_tmax_in_crop: false
    default_crop_tmin: null
    default_crop_tmax: null
    pain_color: "crimson"
    nonpain_color: "navy"
    plots_subdir: "01_foundational_analysis"
    counts_file_name: "counts_pain.tsv"
    output_files:
      pain_gfp: "erp_pain_binary_gfp.png"
      pain_butterfly: "erp_pain_binary_butterfly.png"
      temp_gfp: "erp_by_temperature_gfp.png"
      temp_butterfly: "erp_by_temperature_butterfly.png"
      temp_butterfly_template: "erp_by_temperature_butterfly_{label}.png"

time_frequency_analysis:
  baseline_window: [-5.0, -0.01]
  plateau_window: [3.0, 10.5]
  # Output units for baseline-corrected TFR values derived from log ratios.
  # Options:
  #   - "logratio": plain log10(power/baseline)
  #   - "dB": 10*log10(power/baseline)
  output_units: "dB"
  tfr:
    freq_min: 1.0
    freq_max: 100.0
    n_freqs: 40
    n_cycles_factor: 2.0
    decim: 4
    picks: "eeg"
  bands:
    theta: [4.0, 7.9]
    alpha: [8.0, 12.9]
    beta: [13.0, 30.0]
    gamma: [30.1, 80.0]
  rois:
    Frontal: ["^(Fpz|Fp[12]|AFz|AF[3-8]|Fz|F[1-8])$"]
    Central: ["^(Cz|C[1-6])$"]
    Parietal: ["^(Pz|P[1-8])$"]
    Occipital: ["^(Oz|O[12]|POz|PO[3-8])$"]
    Temporal: ["^(T7|T8|TP7|TP8|FT7|FT8)$"]
    Sensorimotor:
      - "^(FC[234]|FCz)$"
      - "^(C[234]|Cz)$"
      - "^(CP[234]|CPz)$"
  roi_mask_params:
    marker: 'o'
    markerfacecolor: 'w'
    markeredgecolor: 'k'
    linewidth: 0.5
    markersize: 4
  min_baseline_samples: 5

feature_engineering:
  min_baseline_samples: 5
  tfr_spectrogram_vlim: null
  save_tfr_with_sidecar: false

raw_to_bids:
  default_montage: "easycap-M1"
  default_line_freq: 60.0

behavior_analysis:
  # Time-frequency heatmap defaults
  time_frequency_heatmap:
    time_resolution: 0.1
    freq_resolution: 2.0
    time_window: [0.0, 10.5]
    freq_range: [4.0, 80.0]
    alpha: 0.05
    roi_selection: null
    n_cycles_factor: 2.0
    decim: 4
    min_valid_points: 5
  # Spline smoothing for diagnostics
  spline:
    smoothing_factor: 0.3
    min_smoothing: 1.0
    max_iter: 50
    tolerance: 1e-3
  # Statistics defaults
  statistics:
    bootstrap_n: 1000
    min_correlation_samples: 10
    fdr_alpha: 0.05
  predictors:
    top_n: 20
  visualization:
    smoothing_sigma: 2.0

decoding:
  cv:
    inner_splits: 5
  models:
    elasticnet:
      max_iter: 200000
      tol: 1e-3
      selection: "random"
      grid:
        alpha: [1e-3, 1e-2, 1e-1, 1, 10, 100]
        l1_ratio: [0.2, 0.5, 0.8]
    random_forest:
      n_estimators: 500
      estimator_n_jobs: -1
      bootstrap: true
      grid:
        max_depth: [null, 8, 16, 32]
        max_features: ["sqrt", 0.2, 0.5, 1.0]
        min_samples_leaf: [1, 5, 10]
    temperature_only:
      ridge_alpha_grid: [0.0, 1e-3, 1e-2, 1e-1, 1, 10]
  analysis:
    n_perm_quick: 1000
    n_perm_refit: 500
    rf_perm_importance_repeats: 20
    bootstrap_n: 1000
    riemann:
      plateau_window: [3.0, 10.5]
      bands: [[1.0, 4.0], [4.0, 8.0], [8.0, 13.0], [13.0, 30.0], [30.0, 45.0]]
      sliding_window:
        window_len: 0.75
        step: 0.25
  flags:
    run_within_subject_kfold: true
    run_riemann: true
    run_shap: true
  paths:
    results_subdir: "decoding"
    plots_subdir: "plots"
    indices:
      elasticnet_loso: "elasticnet_loso_indices.tsv"
      elasticnet_within: "elasticnet_within_kfold_indices.tsv"
      rf_loso: "rf_loso_indices.tsv"
      rf_within: "rf_within_kfold_indices.tsv"
      riemann_loso: "riemann_loso_indices.tsv"
      riemann_band_template: "riemann_loso_indices_{label}.tsv"
      temperature_only: "temperature_only_loso_indices.tsv"
      baseline_global: "baseline_global_loso_indices.tsv"
      diagnostic_subject_test_mean: "diagnostic_subject_test_mean_loso_indices.tsv"
    best_params:
      elasticnet_loso: "best_params_elasticnet.jsonl"
      elasticnet_within: "best_params_elasticnet_within.jsonl"
      rf_loso: "best_params_rf.jsonl"
      rf_within: "best_params_rf_within.jsonl"
      temperature_only: "best_params_temperature_only.jsonl"
      riemann_loso: "best_params_riemann.jsonl"
      riemann_band_template: "best_params_riemann_{label}.jsonl"
    predictions:
      elasticnet_loso: "elasticnet_loso_predictions.tsv"
      elasticnet_within: "elasticnet_within_kfold_predictions.tsv"
      rf_loso: "rf_loso_predictions.tsv"
      rf_within: "rf_within_kfold_predictions.tsv"
      baseline_global: "baseline_global_loso_predictions.tsv"
      diagnostic_subject_test_mean: "diagnostic_subject_test_mean_loso_predictions.tsv"
      temperature_only: "temperature_only_loso_predictions.tsv"
      riemann_loso: "riemann_loso_predictions.tsv"
      riemann_band_template: "riemann_loso_predictions_{label}.tsv"
    per_subject_metrics:
      elasticnet_loso: "elasticnet_per_subject_metrics.tsv"
      elasticnet_within: "elasticnet_within_kfold_per_subject_metrics.tsv"
      rf_loso: "rf_per_subject_metrics.tsv"
      rf_within: "rf_within_kfold_per_subject_metrics.tsv"
      baseline_global: "baseline_global_per_subject_metrics.tsv"
      diagnostic_subject_test_mean: "diagnostic_subject_test_per_subject_metrics.tsv"
      riemann_loso: "riemann_per_subject_metrics.tsv"
      temperature_only: "temperature_only_per_subject_metrics.tsv"
    summaries:
      bootstrap: "summary_bootstrap.json"
      incremental: "summary_incremental.json"
      permutation_refit_null_rs: "permutation_refit_null_rs.txt"
      permutation_refit_summary: "permutation_refit_summary.json"
      summary: "summary.json"
      all_metrics_wide: "all_metrics_wide.tsv"
      riemann_bands: "summary_riemann_bands.json"
      riemann_sliding_window: "riemann_sliding_window.json"

statistics:
  use_spearman_default: true
  partial_covars_default: null
  n_perm_default: 0
  do_group_default: false
  group_only_default: false
  build_reports_default: true

random:
  seed: 42
  bootstrap_default: 0

logging:
  type: "file"
  level: "INFO"
  file_names:
    foundational: "01_foundational_analysis.log"
    time_frequency: "02_time_frequency_analysis.log"
    feature_engineering: "03_feature_engineering.log"
    behavior_analysis: "04_behavior_feature_analysis.log"
    decoding: "05_decode_pain_experience.log"

environment:
  thread_limits:
    OMP_NUM_THREADS: "1"
    MKL_NUM_THREADS: "1"
    OPENBLAS_NUM_THREADS: "1"
    NUMEXPR_NUM_THREADS: "1"
